version: 2

models:
  - name: stg_listing_history
    description: Daily AirBnB listings availability in Colorado
    columns:
      - name: id
        description: primary key
        tests:
          - not_null
          - unique

  - name: stg_listings
    description: Model of AirBnB listings in Colorado
    columns:
      - name: listing_id
        description: primary key
        tests:
          - not_null
          - unique

  - name: stg_reviews
    description: Model of AirBnB reviews in Colorado
    columns:
      - name: review_id
        description: primary key
        tests:
          - not_null
          - unique
